# Site settings
title: jedevc
email: jedevc@gmail.com
description: >-
  Randomly hacking things together until they work.
baseurl: ""
url: ""
twitter_username: jedevc
github_username:  jedevc

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
